/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StrafhegySocial_uint32Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPosition"
      | "confidentialProtocolId"
      | "creatorActive"
      | "getAllCreators"
      | "getCreatorAt"
      | "getCreatorCount"
      | "getPosition"
      | "getPositionCount"
      | "monthlyPriceWei"
      | "refreshAccess"
      | "subscribe"
      | "subscriptionExpiry"
      | "updatePositionStatus"
      | "upsertProfile"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PositionAdded"
      | "PositionStatusUpdated"
      | "ProfileUpserted"
      | "Subscribed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addPosition",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creatorActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCreators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyPriceWei",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refreshAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionExpiry",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePositionStatus",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upsertProfile",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "addPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCreators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyPriceWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refreshAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePositionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upsertProfile",
    data: BytesLike
  ): Result;
}

export namespace PositionAddedEvent {
  export type InputTuple = [creator: AddressLike, positionId: BigNumberish];
  export type OutputTuple = [creator: string, positionId: bigint];
  export interface OutputObject {
    creator: string;
    positionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionStatusUpdatedEvent {
  export type InputTuple = [creator: AddressLike, positionId: BigNumberish];
  export type OutputTuple = [creator: string, positionId: bigint];
  export interface OutputObject {
    creator: string;
    positionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpsertedEvent {
  export type InputTuple = [
    creator: AddressLike,
    monthlyPriceWei: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    creator: string,
    monthlyPriceWei: bigint,
    active: boolean
  ];
  export interface OutputObject {
    creator: string;
    monthlyPriceWei: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    subscriber: AddressLike,
    creator: AddressLike,
    expiresAt: BigNumberish,
    paidWei: BigNumberish
  ];
  export type OutputTuple = [
    subscriber: string,
    creator: string,
    expiresAt: bigint,
    paidWei: bigint
  ];
  export interface OutputObject {
    subscriber: string;
    creator: string;
    expiresAt: bigint;
    paidWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrafhegySocial_uint32 extends BaseContract {
  connect(runner?: ContractRunner | null): StrafhegySocial_uint32;
  waitForDeployment(): Promise<this>;

  interface: StrafhegySocial_uint32Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPosition: TypedContractMethod<
    [
      coinCodeEnc: BytesLike,
      expectationEnc: BytesLike,
      entryPriceEnc: BytesLike,
      openedAtEnc: BytesLike,
      targetEnc: BytesLike,
      statusEnc: BytesLike,
      deadline: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  creatorActive: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getAllCreators: TypedContractMethod<[], [string[]], "view">;

  getCreatorAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getCreatorCount: TypedContractMethod<[], [bigint], "view">;

  getPosition: TypedContractMethod<
    [creator: AddressLike, positionId: BigNumberish],
    [
      [string, string, string, string, string, string, boolean] & {
        coinCode: string;
        expectation: string;
        entryPrice: string;
        openedAt: string;
        target: string;
        status: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getPositionCount: TypedContractMethod<
    [creator: AddressLike],
    [bigint],
    "view"
  >;

  monthlyPriceWei: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  refreshAccess: TypedContractMethod<
    [creator: AddressLike],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<[creator: AddressLike], [void], "payable">;

  subscriptionExpiry: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  updatePositionStatus: TypedContractMethod<
    [
      positionId: BigNumberish,
      statusEnc: BytesLike,
      deadline: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  upsertProfile: TypedContractMethod<
    [priceWei: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPosition"
  ): TypedContractMethod<
    [
      coinCodeEnc: BytesLike,
      expectationEnc: BytesLike,
      entryPriceEnc: BytesLike,
      openedAtEnc: BytesLike,
      targetEnc: BytesLike,
      statusEnc: BytesLike,
      deadline: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorActive"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllCreators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCreatorAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCreatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [creator: AddressLike, positionId: BigNumberish],
    [
      [string, string, string, string, string, string, boolean] & {
        coinCode: string;
        expectation: string;
        entryPrice: string;
        openedAt: string;
        target: string;
        status: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPositionCount"
  ): TypedContractMethod<[creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "monthlyPriceWei"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "refreshAccess"
  ): TypedContractMethod<[creator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[creator: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "subscriptionExpiry"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "updatePositionStatus"
  ): TypedContractMethod<
    [
      positionId: BigNumberish,
      statusEnc: BytesLike,
      deadline: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upsertProfile"
  ): TypedContractMethod<
    [priceWei: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PositionAdded"
  ): TypedContractEvent<
    PositionAddedEvent.InputTuple,
    PositionAddedEvent.OutputTuple,
    PositionAddedEvent.OutputObject
  >;
  getEvent(
    key: "PositionStatusUpdated"
  ): TypedContractEvent<
    PositionStatusUpdatedEvent.InputTuple,
    PositionStatusUpdatedEvent.OutputTuple,
    PositionStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpserted"
  ): TypedContractEvent<
    ProfileUpsertedEvent.InputTuple,
    ProfileUpsertedEvent.OutputTuple,
    ProfileUpsertedEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;

  filters: {
    "PositionAdded(address,uint256)": TypedContractEvent<
      PositionAddedEvent.InputTuple,
      PositionAddedEvent.OutputTuple,
      PositionAddedEvent.OutputObject
    >;
    PositionAdded: TypedContractEvent<
      PositionAddedEvent.InputTuple,
      PositionAddedEvent.OutputTuple,
      PositionAddedEvent.OutputObject
    >;

    "PositionStatusUpdated(address,uint256)": TypedContractEvent<
      PositionStatusUpdatedEvent.InputTuple,
      PositionStatusUpdatedEvent.OutputTuple,
      PositionStatusUpdatedEvent.OutputObject
    >;
    PositionStatusUpdated: TypedContractEvent<
      PositionStatusUpdatedEvent.InputTuple,
      PositionStatusUpdatedEvent.OutputTuple,
      PositionStatusUpdatedEvent.OutputObject
    >;

    "ProfileUpserted(address,uint256,bool)": TypedContractEvent<
      ProfileUpsertedEvent.InputTuple,
      ProfileUpsertedEvent.OutputTuple,
      ProfileUpsertedEvent.OutputObject
    >;
    ProfileUpserted: TypedContractEvent<
      ProfileUpsertedEvent.InputTuple,
      ProfileUpsertedEvent.OutputTuple,
      ProfileUpsertedEvent.OutputObject
    >;

    "Subscribed(address,address,uint32,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
  };
}
